exclude: "^docs/|/migrations/"
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: no-commit-to-branch
        stages: [pre-push, pre-merge-commit]
        args: ["-p", "production"]

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
