#!/bin/bash

if [ ! -d "./projects" ]; then
  echo "Not found projects dir, creating..."
  mkdir projects
fi


cd ./projects

if [ ! -d "./movix-admin" ]; then
  echo "Not found movix-admin repo, cloning..."
  git clone git@github.com:stranded-in-python/movix-admin.git
else
  echo "Updating movix-admin..."
  cd movix-admin
  if [ ! -f ".git/hooks/pre-push" ]; then
    cp -f ../../.githooks/pre-push .git/hooks/
  fi
  git fetch
  git stash
  git checkout main
  git pull origin main
  echo "Stashed changes, pulled and checked out movix-admin/main"
  cd ..
fi

if [ ! -d "./movix-etl" ]; then
  git clone git@github.com:stranded-in-python/movix-etl.git
  python3.11 -m venv venv
else
  echo "Updating movix-etl..."
  cd movix-etl
  if [ ! -f ".git/hooks/pre-push" ]; then
    cp -f ../../.githooks/pre-push .git/hooks/
  fi
  git fetch
  git stash
  git checkout main
  git pull origin main
  echo "Stashed changes, pulled and checked out movix-etl/main"
  cd ..
fi

if [ ! -d "./movix-api" ]; then
  echo "Not found movix-api repo, cloning..."
  git clone git@github.com:stranded-in-python/movix-api.git
else
  echo "Updating movix-api..."
  cd movix-api
  if [ ! -f ".git/hooks/pre-push" ]; then
    cp -f ../../.githooks/pre-push .git/hooks/
  fi
  git fetch
  git stash
  git checkout main
  git pull origin main
  echo "Stashed changes, pulled and checked out movix-api/main"
  cd ..
fi

if [ ! -d "./movix-auth" ]; then
  echo "Not found movix-auth repo, cloning..."
  git clone git@github.com:stranded-in-python/movix-auth.git
else
  echo "Updating movix-auth..."
  cd movix-auth
  if [ ! -f ".git/hooks/pre-push" ]; then
    cp -f ../../.githooks/pre-push .git/hooks/
  fi
  git fetch
  git stash
  git checkout main
  git pull origin main
  echo "Stashed changes, pulled and checked out movix-auth/main"
  cd ..
fi

if [ ! -d "./movix-ugc" ]; then
  echo "Not found movix-ugc repo, cloning..."
  git clone git@github.com:stranded-in-python/movix-ugc.git
else
  echo "Updating movix-ugc..."
  cd movix-ugc
  if [ ! -f ".git/hooks/pre-push" ]; then
    cp -f ../../.githooks/pre-push .git/hooks/
  fi
  git fetch
  git stash
  git checkout main
  git pull origin main
  echo "Stashed changes, pulled and checked out movix-ugc/main"
  cd ..
fi


cd ..
