version: "3.8"

name: "movix-local"

volumes:
  postgres_data_local: {}
  elastic_data_local: {}
  redis_data_local: {}
  clickhouse_data_local: {}
  logstash_data: {}
  nginx_logs: {}

services:
  postgres:
    image: postgres:14
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    profiles:
      - "admin"
      - "all"
      - "auth"
      - "etl"
      - "init"

  admin:
    build:
      context: ./projects/movix-admin/
      dockerfile: ./compose/local/django/Dockerfile
    image: movix_admin
    depends_on:
      - postgres
    volumes:
      - ./projects/movix-admin/admin:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    stdin_open: true
    command: "/start"
    ports:
      - "8000:8000"
    profiles:
      - "admin"
      - "all"
      - "init"
      - "notification"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: admin

  redis:
    image: redis:7.2-rc-bullseye
    volumes:
      - redis_data_local:/data
    ports:
      - "6379:6379"

  elastic:
    image: elasticsearch:8.7.0
    volumes:
      - elastic_data_local:/usr/share/elasticsearch/data
    env_file:
      - ./.envs/.local/.elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    profiles:
      - "all"
      - "api"
      - "etl"
      - "logging"

  logstash:
    image: elastic/logstash:8.7.0
    env_file:
      - ./envs/.local/.logstash
    volumes:
      - ./compose/production/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./compose/production/logstash/conf.d/:/etc/logstash/conf.d/:ro
    ports:
      - "9045:5045"
    profiles:
      - "all"
      - "logging"

  kibana:
    image: elastic/kibana:8.7.0
    ports:
      - "5601:5601"
    depends_on:
      - elastic
    profiles:
      - "all"
      - "logging"

  s2p:
    build:
      context: ./projects/movix-admin/
      dockerfile: ./compose/production/sqlite_to_postgres/Dockerfile
    image: yamp_s2p
    stdin_open: true
    depends_on:
      - admin
      - postgres
    command: "/start"
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.django
    profiles:
      - "admin"
      - "all"
      - "init"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: s2p

  etl:
    build:
      context: ./projects/movix-etl/
      dockerfile: ./compose/local/etl/Dockerfile
    stdin_open: true
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.django
    command: "/start"
    volumes:
      - ./projects/movix-etl/src/:/app:z
    profiles:
      - "all"
      - "etl"
      - "init"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: etl

  api:
    build:
      context: ./projects/movix-api/
      dockerfile: ./compose/local/api/Dockerfile
    image: movix_api
    stdin_open: true
    depends_on:
      - elastic
    command: "/start"
    volumes:
      - ./projects/movix-api/src:/app:z
    env_file:
      - ./.envs/.local/.api
    ports:
      - "8001:8000"
    profiles:
      - "all"
      - "api"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: api

  auth:
    build:
      context: ./projects/movix-auth/
      dockerfile: ./compose/local/auth/Dockerfile
    image: movix_auth
    stdin_open: true
    depends_on:
      - postgres
      - redis
    command: "/start"
    volumes:
      - ./projects/movix-auth/src:/app:z
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.auth
    ports:
      - "8002:8000"
    profiles:
      - "all"
      - "auth"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: auth

  jaeger:
    image: jaegertracing/all-in-one:1.46.0
    ports:
      - "6831:6831"
      - "16686:16686"
    profiles:
      - "all"
      - "tracing"

  nginx:
    image: nginx:stable-alpine3.17
    volumes:
      - ./compose/local/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./compose/local/nginx/configs:/etc/nginx/conf.d:ro
      - nginx_logs:/var/log/nginx/
    ports:
      - "8005:80"
    profiles:
      - "all"
      - "nginx"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: nginx

  ugc-api:
    build:
      context: ./projects/movix-ugc/
      dockerfile: ./compose/local/api/Dockerfile
    command: "/start"
    ports:
      - "8003:8000"
    env_file:
      - ./.envs/.local/.ugc
    profiles:
      - "all"
      - "ugc-api"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: ugc-api

  clickhouse:
    build:
      context: ./projects/movix-ugc/
      dockerfile: ./compose/local/clickhouse/Dockerfile
    env_file:
      - ./.envs/.local/.clickhouse
    volumes:
      - clickhouse_data_local:/var/lib/clickhouse
    ports:
      - "18123:8123"
    profiles:
      - "all"
      - "ugc-etl"
