version: "3.8"

volumes:
  clickhouse_data: {}
  postgres_data: {}
  elastic_data: {}
  redis_data: {}
  static_data: {}

services:
  postgres:
    image: postgres:14
    env_file:
      - ./.envs/.production/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  admin:
    image: ghcr.io/stranded-in-python/movix-admin:latest
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    volumes:
      - static_data:/app/staticfiles
    stdin_open: true
    command: "/start"

  redis:
    image: redis:7.2-rc-bullseye
    volumes:
      - redis_data:/data

  elastic:
    image: elasticsearch:8.7.0
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    env_file:
      - ./.envs/.production/.elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1

  s2p:
    image: ghcr.io/stranded-in-python/movix-s2p:latest
    depends_on:
      - admin
      - postgres
    command: "/start"
    env_file:
      - ./.envs/.production/.postgres
      - ./.envs/.production/.django

  etl:
    image: ghcr.io/stranded-in-python/movix-etl:latest
    restart: always
    depends_on:
      - postgres
      - elastic
      - admin
      - s2p
      - redis
    env_file:
      - ./.envs/.production/.postgres
      - ./.envs/.production/.django
    command: "/start"

  api:
    image: ghcr.io/stranded-in-python/movix-api:latest
    depends_on:
      - elastic
    command: "/start"
    env_file:
      - ./.envs/.production/.api

  auth:
    image: ghcr.io/stranded-in-python/movix-etl:latest
    depends_on:
      - postgres
      - redis
    command: "/start"
    env_file:
      - ./.envs/.production/.auth
      - ./.envs/.production/.postgres

  jaeger:
    image: jaegertracing/all-in-one:1.46.0

  nginx:
    image: nginx:latest
    depends_on:
      - postgres
      - admin
      - api
      - etl
      - auth
    volumes:
      - ./compose/production/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./compose/production/nginx/configs:/etc/nginx/conf.d:ro
      - static_data:/data
    ports:
      - "80:80"

  clickhouse:
    build:
      context: ./projects/movix-ugc/
      dockerfile: ./compose/production/clickhouse/Dockerfile
    env_file:
      - ./.envs/.production/.clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  ugc-api:
    image: ghcr.io/stranded-in-python/movix-ugc:latest
    command: "/start"
    env_file:
      - ./.envs/.production/.ugc

  ugc-etl:
    image: ghcr.io/stranded-in-python/movix-etl:latest
    command: "/start"
    env_file:
      - ./.envs/.produciton/.clickhouse
      - ./.envs/.production/.ugc
