version: "3.8"

services:
  ugc-etl-watching:
    build:
      context: ./projects/movix-ugc/
      dockerfile: ./compose/local/etl/watching/Dockerfile
    command: "/start"
    env_file:
      - ./.envs/.local/.clickhouse
      - ./.envs/.local/.ugc
    restart: always
    profiles:
      - "all"
      - "ugc-etl"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: ugc-etl-watching

  ugc-etl-bookmarks:
    build:
      context: ./projects/movix-ugc/
      dockerfile: ./compose/local/etl/bookmarks/Dockerfile
    command: "/start"
    env_file:
      - ./.envs/.local/.clickhouse
      - ./.envs/.local/.ugc
    restart: always
    profiles:
      - "all"
      - "ugc-etl"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: ugc-etl-bookmarks

  ugc-etl-reviews:
    build:
      context: ./projects/movix-ugc/
      dockerfile: ./compose/local/etl/reviews/Dockerfile
    command: "/start"
    env_file:
      - ./.envs/.local/.clickhouse
      - ./.envs/.local/.ugc
    restart: always
    profiles:
      - "all"
      - "ugc-etl"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: ugc-etl-reviews

  ugc-etl-likes_movies:
    build:
      context: ./projects/movix-ugc/
      dockerfile: ./compose/local/etl/likes_movies/Dockerfile
    command: "/start"
    env_file:
      - ./.envs/.local/.clickhouse
      - ./.envs/.local/.ugc
    restart: always
    profiles:
      - "all"
      - "ugc-etl"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: ugc-etl-likes_movies

  ugc-etl-likes_reviews:
    build:
      context: ./projects/movix-ugc/
      dockerfile: ./compose/local/etl/likes_reviews/Dockerfile
    command: "/start"
    env_file:
      - ./.envs/.local/.clickhouse
      - ./.envs/.local/.ugc
    restart: always
    profiles:
      - "all"
      - "ugc-etl"
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5045
        tag: ugc-etl-likes_reviews
